# AUTH DATABASE
spring.datasource.auth.url=jdbc:mysql://localhost:3306/spms_auth_db?createDatabaseIfNotExist=true
spring.datasource.auth.username=root
spring.datasource.auth.password=root
spring.datasource.auth.driver-class-name=com.mysql.cj.jdbc.Driver

# APP DATABASE
spring.datasource.app.url=jdbc:mysql://localhost:3306/spms_db?createDatabaseIfNotExist=true
spring.datasource.app.username=root
spring.datasource.app.password=root
spring.datasource.app.driver-class-name=com.mysql.cj.jdbc.Driver

# Disable single-datasource auto config
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# JWT
jwt.secret=spms-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000